name: Docker Image CI - using quay


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    environment:
      name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build & push the Docker image
        env:
          CF_IMAGE: quay.io/${{ secrets.QUAY_USERNAME }}/quay-github-action-example
        run: |
          docker build . --file Dockerfile --tag $CF_IMAGE && docker push $CF_IMAGE
          echo "Image should be accessible to your local machine (after docker login) by:"
          echo "docker pull $CF_IMAGE"
          docker pull $CF_IMAGE
          echo "On the next step, the report image would use the integration to pull information on the reported image, and using the specified enrichers."
      - name: report image by action
        with:
          # Specify cluster app-proxy
          CF_HOST: "${{ secrets.CF_HOST_RUNTIME }}"
          CF_API_KEY: ${{ secrets.USER_TOKEN }}
          # CF_CONTAINER_REGISTRY_INTEGRATION: "quay"
          CF_REGISTRY_USERNAME: "${{ secrets.QUAY_USERNAME }}" 
          CF_REGISTRY_PASSWORD: "${{ secrets.QUAY_PASSWORD }}"
          CF_REGISTRY_DOMAIN: "quay.io"

          # report image 
          CF_IMAGE: ${{ secrets.QUAY_USERNAME }}/quay-report-image-github-action
          CF_ENRICHERS: "jira, git"
          # use githug token
          CF_GITHUB_TOKEN: ${{ secrets.CF_GITHUB_TOKEN }}    
          # use jira integration - jira is the name of the integration created in codefresh argo platform.
          CF_JIRA_INTEGRATION: "jira" 
          CF_JIRA_MESSAGE: "A message with embedded issue ( i.e. CR-11027 ) that would be use query jira for the ticket "
          # a specified prefix for finding the jira issue 
          CF_JIRA_PROJECT_PREFIX: "CR"
        uses: codefresh-io/codefresh-report-image@Marketplace


