name: Docker Image CI

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
on:
  pull_request
jobs:
  build:
    environment:
      name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: 'quay.io'
          username: ${{ secrets.DOCKERQUAY_USERNAME }}
          password: ${{ secrets.DOCKERQUAY_TOKEN }}
      - name: Build & push the Docker image
        env:
          CF_IMAGE: 'quay.io/${{ secrets.DOCKERQUAY_USERNAME }}/denis:10.0.0'
        run: |
          docker build . --file Dockerfile --tag $CF_IMAGE && docker push $CF_IMAGE
          
          
      - name: report image
        with:
          # Name of runtime to implement the enrichment
#           CF_HOST: 'https://mr-60c7443e37ca2730b9757992-e4c9118.cf-cd.com'

          CF_RUNTIME_NAME: 'codefresh-hosted'
          # Codefresh API key !! Committing a plain text token is a security risk. We highly recommend using an encrypted secrets. !!
          # Documentation - https://docs.github.com/en/actions/security-guides/encrypted-secrets
        
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          # Name of Container registry integration
          CF_CONTAINER_REGISTRY_INTEGRATION: 'hosted-quay-new'

          # Name of Jira integration
          CF_JIRA_INTEGRATION: 'eti-jira-new'

          # Image path to enrich
          CF_IMAGE: 'quay.io/${{ secrets.DOCKERQUAY_USERNAME }}/denis:10.0.0'

          # GitHub Access token !! Committing a plain text token is a security risk. We highly recommend using an encrypted secrets. !!
          # Documentation - https://docs.github.com/en/actions/security-guides/encrypted-secrets
          CF_GITHUB_TOKEN: ${{ secrets.G_TOKEN }}

          # Jira project filter
          CF_JIRA_PROJECT_PREFIX: "CR"

          # String starting with the issue ID to associate with image
          CF_JIRA_MESSAGE: "CR-11028"
          
#           CF_WORKFLOW_NAME: "test"

#         uses: codefresh-io/codefresh-report-image@latest
        uses: eti-codefresh/codefresh-report-image@test8
          


